# Generated by Django 2.2.18 on 2021-02-07 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='administrator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='org', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
            preserve_default=False,
        ),
    ]
