# Generated by Django 2.2.18 on 2021-02-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_administrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '市区', 'verbose_name_plural': '市区'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': '县', 'verbose_name_plural': '县'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': '组织', 'verbose_name_plural': '组织'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name': '村', 'verbose_name_plural': '村'},
        ),
    ]
