# Generated by Django 2.2.18 on 2021-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210207_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': '留守儿童', 'verbose_name_plural': '留守儿童'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': '组织管理员', 'verbose_name_plural': '组织管理员'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': '志愿者', 'verbose_name_plural': '志愿者'},
        ),
        migrations.AddField(
            model_name='organization',
            name='inviteCode',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='邀请码'),
        ),
    ]
