# Generated by Django 2.2.18 on 2021-02-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210208_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'permissions': (('view_pair', '可以查看结对另一方的信息'),), 'verbose_name': '留守儿童', 'verbose_name_plural': '留守儿童'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('add_members', '可以添加人员'), ('remove_members', '可以移除人员')), 'verbose_name': '组织', 'verbose_name_plural': '组织'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'permissions': (('view_pair', '可以查看结对另一方的信息'),), 'verbose_name': '志愿者', 'verbose_name_plural': '志愿者'},
        ),
    ]
