# Generated by Django 2.2.18 on 2021-02-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210208_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='行政区划代码')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='单位名称')),
            ],
            options={
                'verbose_name': '行政区',
                'verbose_name_plural': '行政区',
            },
        ),
        migrations.RemoveField(
            model_name='child',
            name='county',
        ),
        migrations.RemoveField(
            model_name='child',
            name='village',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='county',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='village',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='county',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='village',
        ),
        migrations.AlterField(
            model_name='child',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.AdminDiv', verbose_name='行政区'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.AdminDiv', verbose_name='行政区'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.AdminDiv', verbose_name='行政区'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
