# Generated by Django 2.2.18 on 2021-02-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210208_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='city',
            new_name='adminDiv',
        ),
        migrations.RenameField(
            model_name='manager',
            old_name='city',
            new_name='adminDiv',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='city',
            new_name='adminDiv',
        ),
    ]
