# Generated by Django 2.2.18 on 2021-02-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210208_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
