# Generated by Django 2.2.18 on 2021-02-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210209_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人住址'),
        ),
        migrations.AlterField(
            model_name='child',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='个人情况介绍'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人住址'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='个人住址'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='个人简介'),
        ),
    ]
