# Generated by Django 2.2.18 on 2021-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210210_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='isActive',
            field=models.CharField(choices=[('0', '不活跃'), ('1', '活跃')], default='0', max_length=1, verbose_name='是否处于激活状态'),
        ),
    ]
