# Generated by Django 2.2.18 on 2021-03-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_organization_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='organization',
            name='adminDiv',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='accounts.AdminDiv', verbose_name='所处的行政区'),
            preserve_default=False,
        ),
    ]
