# Generated by Django 2.2.18 on 2021-02-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('growUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='发表日期')),
                ('body', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('pv', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='评论')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='growUp.Plan', verbose_name='为展示的帮扶')),
            ],
            options={
                'verbose_name': '风采展示',
                'verbose_name_plural': '风采展示',
            },
        ),
    ]
