# Generated by Django 2.2.18 on 2021-02-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pair',
            options={'permissions': (('update_pair_state', '可以修改结对的状态信息'),), 'verbose_name': '结对情况', 'verbose_name_plural': '结对情况'},
        ),
    ]
